# Generated by Django 4.2 on 2024-05-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_list", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
