# Generated by Django 4.2 on 2024-08-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
