# Generated by Django 4.2 on 2024-10-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_post_file_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
    ]
